Algoritmo "se_aninhado"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/04/2025
Var
// Seção de Declarações das variáveis 
nota:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite a nota do aluno")
leia(nota)
se nota>=9 então
escreval("conceito A")
senao
se nota>=7 então
fimse
escreval("voce é menor de idade")
fimse

Fimalgoritmo