Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2025
Var
// Seção de Declarações das variáveis 
senha:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite sua senha")
leia (senha)
enquanto senha<>1577 faca
escreval("tente novamente")
leia (senha)


fimenquanto
   escreval("acesso liberado")

Fimalgoritmo